/* eslint-disable @typescript-eslint/no-explicit-any */
export type ConfigType = {
	appName: string,
	appSiteInfo: any,
	appToken: string,
	appPlugin: boolean,
	appStatus: string,
	appDebug: boolean,
	appUrl: string,
	appUrlAppList: string,
	appUrlTreeDbs: string,
	appUrlTreeTbl: string,
	appUrlTreeVws: string,
	appUrlTreeCls: string,
	appUrlTreeIdx: string,
	appUrlTreeFrk: string,
	appUrlTreeTrg: string,
	appUrlTreeFnc: string,
	appUrlTreePrc: string,
	appUrlMeta: string,
	appUrlGet: string,
	appUrlLov: string,
	appUrlSelect: string,
	appUrlInsert: string,
	appUrlUpdate: string,
	appUrlDelete: string,
	appUrlTable: string,
	appUrlSettings: string,
	appUrlActionRename: string,
	appUrlActionCopy: string,
	appUrlActionTruncate: string,
	appUrlActionDrop: string,
	appOrig: any,
}