export type StoreFormSpacingType = {
	aroundGridTop: number | undefined,
	aroundGridTopUnit: string | undefined,
	aroundGridBottom: number | undefined,
	aroundGridBottomUnit: string | undefined,
	aroundGridLeft: number | undefined,
	aroundGridLeftUnit: string | undefined,
	aroundGridRight: number | undefined,
	aroundGridRightUnit: string | undefined,
	betweenCells: number | undefined,
	betweenCellsUnit: string | undefined,
	cellTop: number | undefined,
	cellTopUnit: string | undefined,
	cellBottom: number | undefined,
	cellBottomUnit: string | undefined,
	cellLeft: number | undefined,
	cellLeftUnit: string | undefined,
	cellRight: number | undefined,
	cellRightUnit: string | undefined,
	fieldTop: number | undefined,
	fieldTopUnit: string | undefined,
	fieldBottom: number | undefined,
	fieldBottomUnit: string | undefined,
	fieldLeft: number | undefined,
	fieldLeftUnit: string | undefined,
	fieldRight: number | undefined,
	fieldRightUnit: string | undefined,
}